### ISSUE TITLE
Update names for publish commands

### ISSUE THREAD

**Issue by rabrowne85** [pwweb/localisation#2]
In Lines: https://github.com/pwweb/localisation/blob/7ba8bac42af91c8fc8423a04405449e2b9ed39e9/src/LocalisationServiceProvider.php#L64 and https://github.com/pwweb/localisation/blob/7ba8bac42af91c8fc8423a04405449e2b9ed39e9/src/LocalisationServiceProvider.php#L71 suggest changing the publish command "names" to be of the form: `pwweb.localisation.config` and `pwweb.localisation.migrations` so that from the command line we can run `$php artisan vendor:publish --tag=pwweb.localisation.config` or the equivalent for the migrations.

**Comment by frankpde** [comment]
Fixes included in 0.1.4-beta
