### ISSUE TITLE
Normalisation of Namespace

### ISSUE THREAD

**Issue by rabrowne85** [pwweb/localisation#3]
Suggest we normalise the Namespaces across the various packages by changing all references of `PWWeb/` to `PWWEB/` i.e. in the following line.

https://github.com/pwweb/localisation/blob/7ba8bac42af91c8fc8423a04405449e2b9ed39e9/src/LocalisationServiceProvider.php#L14

**Comment by frankpde** [comment]
Fixed as of 0.1.5-beta
