### ISSUE TITLE
Change location of Config File

### ISSUE THREAD

**Issue by rabrowne85** [pwweb/localisation#4]
To align with Artomator, suggest that the config file is published to: `config/pwweb/localisation` as this will be within the same path as the other Artomator config file (keeps the PWWEB config files together in one location).

https://github.com/pwweb/localisation/blob/7ba8bac42af91c8fc8423a04405449e2b9ed39e9/src/LocalisationServiceProvider.php#L62

This will mean updating all references to: `config('localisation')` to `config('pwweb.localisation')`.

https://github.com/pwweb/localisation/blob/7ba8bac42af91c8fc8423a04405449e2b9ed39e9/src/LocalisationServiceProvider.php#L36

**Comment by frankpde** [comment]
Fixed as of 0.1.5-beta
