### ISSUE TITLE
Spatie Permission package missing from require

### ISSUE THREAD

**Issue by rabrowne85** [pwweb/localisation#5]
This package references the [`spatie\laravel-permissions`](https://github.com/spatie/laravel-permission) in the config file. Therefore it should be referenced as a required package in the `composer.json` file, so that it's installed if not already part of the parent package.

**Comment by rabrowne85** [comment]
Looking into this issue a little further, I get the feeling that it's a copy/paste issue. I think you've used a similar config file from the spatie package and as such you're referencing similarly named config properties.

**Comment by frankpde** [comment]
I don't see the reference in any of the current files for 0.1.5-beta. Please confirm.

**Comment by rabrowne85** [comment]
Think this has resolved itself. It was in the config file, but has since been removed.
